config/routes.rb
Rails.application.routes.draw do
  get 'chat' => 'chat#index', as: :chat

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'

  get 'chat/new'
  get 'chat/search'
  post 'chat/search'
  get 'chat/user_found'
  get 'chat/user_not_found'
  # TODO remove proxy
  get 'chat/proxy'

  get 'home/index'

  resources :users

  root 'home#index', as: :home
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  validates :name,  presence: true, length: { maximum: 25 }
  validates :email, presence: true, length: { maximum: 100 }, uniqueness: true,
                    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }
  has_secure_password

  def channel
    # TODO More clever channel name
    # (self.name + self.email).split('.').join.downcase
    '/user01'
    # self.name
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  helper_method :current_user

  def authorize
    redirect_to login_path unless current_user
  end
end

app/controllers/chat_controller.rb
class ChatController < ApplicationController
  def index
    @user = User.new
  end

  def new

  end

  def search
    # If chat/search reloaded
    unless params[:sought_user]
      redirect_to chat_path
      # TODO Find out why redirect_to doesn't exit from action by itself?
      return
    end

    @user = if params[:sought_user][:filter] == 'name'
              User.find_by_name(params[:search])
            elsif params[:sought_user][:filter] == 'email'
              User.find_by_email(params[:search])
            end

    # TODO more clever channels TODO remove proxy !!!!!!!!!!!!!!!!!!!!!!!!!!!
    session[:receiver_channel] = "/#{@user.name}"

    if @user
      render 'success'
    else
      render 'failure'
    end
  end

  def proxy

  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    redirect_to chat_path if session[:user_id]
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    @user = User.find_by_email(params[:email])
    # If the user exists AND the password entered is correct.
    if @user && @user.authenticate(params[:password])
      # Save the user id inside the browser cookie. This is how we keep the user
      # logged in when they navigate around our website.
      session[:user_id] = @user.id
      # TODO more clever channel
      session[:sender_channel] = "/#{@user.name}"
      redirect_to chat_path
    else
    # If user's login doesn't work, send them back to the login form.
      flash[:notice] = 'Incorrect e-mail or password or all together.'
      flash[:email] = @user.email if @user
      redirect_to home_path
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to home_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        # format.html { redirect_to @user, notice: 'User was successfully created.' }
        session[:user_id] = @user.id
        format.html { redirect_to home_path }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chat_helper.rb
module ChatHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/chat/_search_tools.html.erb
<div id="search-tools">
  <%= form_tag chat_search_path do %>
    <%= text_field_tag :search, 'Enter your search query here...', class: 'search-field' %>
    <%= select("sought_user", "filter", ['name', 'email'], { include_blank: false }) %>
    <%= submit_tag "Search" %><br />
  <% end %>
</div>

app/views/chat/_user_found.html.erb
<div class="found-user-info">

  <h3>One user with the specified <%= params[:sought_user][:filter] %> was found.</h3>

  Name:  <%= @user.name %>  </br>
  Email: <%= @user.email %> </br>

  <button type="button" onclick="getFoundUserChannel(this);">Get Channel</button>
  <button type="button" onclick="startConversation(this, '<%= @user.channel %>');">
    Start Conversation
  </button>
  <button type="button">Add to Contacts</button>

  <% # TODO More clever channel name %>
  <div class="found-user-channel">
    /<%= @user.name %>
  </div>
</div>

app/views/chat/_user_not_found.html.erb
<% # TODO %>

<div class="std-div">
  <% # TODO less logic in view %>
  <div class="user-info">
    <h3>
      No user with the specified <%= params[:sought_user][:filter] %> found.
      Try again with another search filter.
    </h3>
  </div>
</div>

app/views/chat/failure.html.erb
<div id="container">

  <div id="search-container">
    <%= render 'search_tools' %>
    <%= render 'user_not_found' %>
  </div>

  <div id="chat-container">

  </div>

  <div id="sending-container">

  </div>

</div>

app/views/chat/index.html.erb
<h1>CHAT</h1>

<div id="container">

  <div id="search-container">
    <%= render 'search_tools' %>
  </div>

  <div id="chat-container">

  </div>

  <div id="sending-container">
    <input id="message-input" type="text"></input>
    <button type="button" onclick="publish();">Send Message</button>
  </div>

</div>


<!-- <div id="chat-container" class="std-div">
  <% # /foo1 and /foo2 %>
  <script>faye('<%= session[:sender_channel] %>', '<%= params[:channel] %>');</script>

  <div id="chat-search" class="std-div">
    <%= button_to 'Search New Contact', { controller: :chat, action: :new }, method: :get %>
  </div>

  <div id="chat-place" class="std-div">

  </div>

  <div id="chat-buttons" class="std-div">
    <input id="chat-message-input" type="text"></input>
    <button type="button" class="send-msg-btn"
        onclick="publish()">Send Message
    </button>
  </div>

</div> -->

app/views/chat/new.html.erb
<%= render 'search_tools' %>

app/views/chat/success.html.erb
<h1>CHAT</h1>

<div id="container">

  <div id="search-container">
    <%= render 'search_tools' %>
    <%= render 'user_found' %>
  </div>

  <div id="chat-container">

  </div>

  <div id="sending-container">
    <input id="message-input" type="text"></input>
    <button type="button" onclick="publish();">Send Message</button>
  </div>

</div>

app/views/chat/user_not_found.html.erb
<%= render 'search_tools' %>

<div class="std-div">
  <% # TODO less logic in view %>
  <div class="user-info">
    <h3>
      No user with the specified <%= params[:sought_user][:filter] %> found.
      Try again with another search filter.
    </h3>
  </div>
</div>

app/views/home/index.html.erb
<h1>Simple Messanger Home Page</h1>

<div class="std-div">
  <h2 id="register-h2">Register</h2>
  <!-- TODO popup registration form -->
  <%= button_to "Sign Up", { controller: 'users', action: 'new' },
    method: :get, form_class: 'register-form' %>
</div>

<div class="std-div">
  <h2 id="login-h2">Login</h2>
  <%= form_tag '/login' do %>
    <% if flash[:notice] %>
      <div id="login-error">
        <%= flash[:notice] %>
      </div>
    <% end %>
    Email:<br />
    <%= text_field_tag :email, flash[:email] || '' %><br />
    Password:<br />
    <%= password_field_tag :password %><br /><br />
    <%= submit_tag "Submit" %><br />
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SimpleMessanger</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <script type="text/javascript" src=<%= "#{home_url}faye/client.js" %> ></script>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="std-head">
      <div id="nav-tools">
        <% if current_user %>
          Signed in as <%= current_user.name %> |
          <%= link_to "Logout", { controller: 'sessions', action: 'destroy' } %>
        <% else %>
          <span onclick="performBlink('login-h2')" id="login-span">Login</span> |
          <span onclick="performBlink('register-h2')" id="register-span">Sign Up</span>
        <% end %>
      </div>
    </div>
    <div>
      <%= yield %>
    </div>
  </body>
</html>

app/views/users/_form.html.erb
<%= form_for(user) do |f| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :email %>
    <%= f.text_field :email %>
  </div>

  <div class="field">
    <%= f.label :password %>
    <%= f.password_field :password %>
  </div>

  <div class="field">
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>